# Generated by Django 3.1.2 on 2021-03-21 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picsfolio', '0004_auto_20210321_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
