# Generated by Django 3.1.2 on 2021-03-21 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picsfolio', '0007_userimage_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='username',
        ),
    ]
