# Generated by Django 3.1.7 on 2021-04-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picsfolio', '0015_usercatalog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercatalog',
            old_name='name',
            new_name='CatalogName',
        ),
    ]
